services:
  frontend:
    build:
      context: ../sproochenFE/luxembourgish-exam-ai-coach
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "4200:80"
  # service name is mysql
  mysql:
    image: mysql:8
    container_name: sproochen-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sproochencoach
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      #"Attach the volume named mysql-data
      #to /var/lib/mysql inside this container."
    volumes:
      - mysql-data:/var/lib/mysql
  backend:
    build: .  #use the current directory as the build context and use the Dockerfile there
    #LEFT  = outside Docker / your PC
    #RIGHT = inside the container
    ports:
      - "8080:8080" #"HOST_PORT:CONTAINER_PORT"  : When my PC receives something on port 8080, forward it to port 8080 inside this container.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
     mysql: #means start mysql container before backend container
      condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
volumes:
  #mysql-data  : the : means use default config
  mysql-data: