spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

stripe.api-key=${STRIPE_API_KEY}
stripe.price-id=${STRIPE_PRICE_ID}
stripe.product-id=${STRIPE_PRODUCT_ID}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}