spring.application.name=sproochenCoach
# Database - dev specific
spring.datasource.url=jdbc:mysql://localhost:3306/sproochencoach?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto= update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.show-sql= true
spring.jpa.generate-ddl=true

security.jwt.secret-key=YOUR_BASE64_SECRET
security.jwt.expiration-time=3600000
###########email config customapppw
# SMTP server configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_APP_PASSWORD}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

security.otp.expiration-ms=300000
